language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: jhonnycgarcia-shareyouridea
  api_key:
    secure: es4tQ/vSaov9T/yLYaqA85f7lCQZFMOhCTQ7diZ8zwB2o+kV8s7t/56qYBgzEWExDeLAKsJPNW64Q6/7bPGQLQiy5+2gavxuyC6KpMt0250cGNkHfqbrDiXQvEs57MskeL4GqIIiblAiGQ98xH7r/8uig+l0v8u7THlvzZ99omrjptt0OT6em8d/ehNulmVxCOjKGRbP9wgT5RSaO999f4vVb+3jdjzChqlNdI+YBALW07+fS8OPxJZotTy/7vE2w9oiFMnGcsSy7hQGoOZ61BGCYJOZJVOAdiApCGVfHSHYDp5AtuQ3Ka7TYUziHmanUVuTGQiRzsrfkh6L+CpO/FCXlZ5XBS3hfeBfNc+akd9MZNCmn87W+nHWV7WnXbv5wrlrO10mRMZz9mQsETGedKwY0MRZSNw/V+kEuhdLXBkPkZttiTC5XVTzoIJZ9iVZRWQG2sCHJXmfmh3yVbE52Vw9KbFWintFA8F1UQFOiFxCrxkNh9p/44WuvJjIgqjHGo+9cmttqvSKlA8XJlKOpksGzthhRcWDL1nIoj1uttJPlaHlzzGQH/68/l48d3US+gVICJvZD8HnSTpZrIgCkOd5B/ICI8JgRlDHfT/5hBIMDGcHJe8IYkY1bZXTumgS3uM4gQhBALGLc4PbfjtdNhrM7nevOWT4g29ilAvN58c=
