language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: jhonnycgarcia-shareyouridea
  api_key:
    secure: nyDwho9H1cfE2B3cN134/0wL/p1k5Bu2J6nhHMvsKILCMzZBLb5tG1sCDNATSVxdyyz/Mc6dVDN9puffP3RRQ9vAzMDBQGyIW5YDimh3EScyrUEkxr0nnXlwxXG9gAUU+jBzXLGSu5wOPRbPZNuwLtxw13sHMWWsFAOHsS7vG61l99Nljdj5QGNgA9ls0kgeFzDzBGoR8k+L0PeQbPZpiK/EY1QlgWNDJB4H7wKiohjdFHDnzZ0tOV8jFpW8EzJE6JfdjIqi/IOwAJ46zFfy/1MCPP6JbbHHksmmbO3ktB71UVeg2tQRL8eHXozFkRMh0V0UibZ+2UT8jAZe7ybb3Qt8Ub4fqDfiGfsbQ23lJ6vFn4J2t1lemgZL6LTC/yMF0MVjQinWmtN5HB6Ad01o+UCAD2iJLUwpMdISZ4NiwQ6UKduJWVXOhbKXcdxNVA5JhHblYTCZz6GKHXpGlUi8A7QToc8IUfJjSgPIMg36jVlry0LM8QV3Rss2L26rvMsK3SWRMjMjJiMIGsL+ZvScZKS9I4Xjt+G7X+rPCEg9VLZKRxmxaJqcbeeZ1PhzMJh8baj40lMD45bQKdltj46TWUpwMvd2cIVBre+fNLjSsR1Ic1JsXxPkGeE48qKBbCJUP0sBx8J61i8oHlkVtUohwDDemEsIjKm7Kc1Qt8O4cTA=
