language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: jhonnycgarcia-shareyouridea
  api_key:
    secure: GCRj11bXUQVK7TPk5m5zj1Fb8jFkWVb82ZiO9bFAeJCaUgVicZtsyB3KzViUo/QGYea1tFxIg8vybY/DeRoWMu3r1RuY1sWea2MI+bNFoMK0Uxp2ByLBngUdkiWMmk4vEbr2pLud4iCfU21gTXq6sl0xTAgB8ZkYQ4jq3Z7bOpD+NLIzNguFfXS8pn3NGw26FgV3y0q0ECB5DsQjjfBA6jKPwZV+TWSF69xRJO3jVkaa8lGR7LeXazxS/a7wJOwto0VboDjU6P2sn5kArIamGQB/Q0mJ84yHAHv5PtyLx1KD9hWG0F6MEuqCTRQAhLostB7RD3mzBA0H3N1+AEUZMtgecZAitv+gkvm5GPbqNZsndz/6QApX4tbHzObY8W0U/rXJpK4+CLwwEvfHSQaZBu1QrIR+KOw6/g69YI6l8A7Y52A7bb2xdjwsYpJzCJU/KlWQK5N8dZTQ2BfJiZVR+gYcd5LxrVfhXuYYTl9ZFcgVnjpbqblhqC+OYEPuZzn8hrTdJtOVR5Y5WLJJnS0oKWbIBZJvChH31yP2uH3ODbvvTCnSDHBYMhycEDllczJ0nNPTCd6FnGBp0kvmSnitwjOzpNCTOELShuRjOP19WXnJLtTiDBQzwJIYC8cjyyIDrVFo6ddqACVzG6blyyKz8B4LjKB5EKbGzBIBtrBqiQM=
